cart/urls.py
from django.urls import path

from cart import views

urlpatterns = [
    path('cart/', views.cart, name='cart'),
    # 加入购物车
    path('add_cart/', views.add_cart, name='add_cart'),
    # 购物车数量的刷新
    path('cart_num/', views.cart_num, name='cart_num'),
    # 总价
    path('cart_price/', views.cart_price, name='cart_price'),
    # 修改购物车的数量/选择状态
    path('change_cart/', views.change_cart, name='change_cart'),
    # 删除购物车
    path('del_cart/<int:id>/', views.del_cart, name='del_cart'),

]

fresh_shop8/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import path, include

from fresh_shop8.settings import MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/',include(('cart.urls', 'cart'), namespace='cart')),
    path('goods/',include(('goods.urls', 'goods'), namespace='goods')),
    path('order/',include(('order.urls', 'order'), namespace='order')),
    path('user/',include(('user.urls', 'user'), namespace='user')),
]

urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

goods/urls.py
from django.urls import path

from goods import views

urlpatterns = [
    path('index/', views.index, name='index'),
    path('detail/<int:id>/', views.detail, name='detail'),
]

order/urls.py
from django.urls import path

from order import views

urlpatterns = [
    path('order', views.order, name='order'),
    # 结算商品
    path('place_order', views.place_order, name='place_order'),
    # 创建订单
    path('make_order/', views.make_order, name='make_order'),

]

user/urls.py
from django.urls import path

from user import views

urlpatterns = [
    # 登录
    path('login/', views.login, name='login'),
    # 注册
    path('register/', views.register, name='register'),
    path('user_center_info/', views.user_center_info, name='user_center_info'),
    # 退出
    path('logout/', views.logout, name='logout'),
    # 收货地址
    path('user_site/', views.user_site, name='user_site'),

]

cart/models.py
from django.db import models

from goods.models import Goods
from user.models import User


class ShoppingCart(models.Model):
    """
    购物车
    """
    user = models.ForeignKey(User, verbose_name='用户', on_delete=models.CASCADE)
    goods = models.ForeignKey(Goods, verbose_name='商品', on_delete=models.CASCADE)
    nums = models.IntegerField(default=0, verbose_name='数量')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='添加时间')
    is_select = models.BooleanField(default=True)

    class Meta:
        db_table = 'f_shopping_cart'

cart/views.py
from unittest import result

from django.http import JsonResponse
from django.shortcuts import render


# 购物车
from cart.models import ShoppingCart
from goods.models import Goods


def cart(requset):
    if requset.method == 'GET':
        # 获取数据
        session_goods = requset.session.get('goods')
        result = []
        for se_goods in session_goods:
            goods = Goods.objects.filter(pk=se_goods[0]).first()
            total_price = goods.shop_price * se_goods[1]
            data = [goods, se_goods[1], se_goods[2], total_price]
            result.append(data)
        return render(requset, 'cart.html', {'result': result})


# 添加商品
def add_cart(requset):
    if requset.method == 'POST':
        # 接收商品id值个商品数量
        # 组装储存格式[goods_id, num , is_select]
        # 组装商品格式[[goods_id, num ,is_select],[goods_id,num,is_select]]
        goods_id = int(requset.POST.get('goods_id'))
        goods_num = int(requset.POST.get('goods_num'))
        goods_list = [goods_id, goods_num, 1]

        session_goods = requset.session.get('goods')
        if session_goods:
            # 添加的商品，则新增

            flag = True
            for se_goods in session_goods:
                if se_goods[0] == goods_id:
                    se_goods[1] += goods_num
                    flag = False
            if flag:
                # 添加重复的商品则修改商品数量
                session_goods.append(goods_list)
            requset.session['goods'] = session_goods
            count = len(session_goods)
        else:
            # 第一次添加
            # 格式为[goods_id, num, is_select]
            requset.session['goods'] = [goods_list]
            count = 1
    return JsonResponse({'code': 200, 'msg': '请求成功', 'count': count})


# 购物车商品数量
def cart_num(requets):
    if requets.method == 'GET':
        session_goods = requets.session.get('goods')
        count = len(session_goods) if session_goods else 0
        return JsonResponse({'code':200, 'msg':'请求成功','count':count})


# 总价
def cart_price(request):
    if request.method == 'GET':
        session_goods = request.session.get('goods')
        all_total = len(session_goods) if session_goods else 0
        all_price = 0
        is_select_num = 0

        for se_goods in session_goods:
            if se_goods[2]:
                goods = Goods.objects.filter(pk=se_goods[0]).first()
                all_price += goods.shop_price * se_goods[1]
                is_select_num += 1
        return JsonResponse({'code':200, 'msg':'请求成功', 'all_price':all_price, 'is_select_num':is_select_num, 'all_total':all_total})


# 修改
def change_cart(request):
    if request.method == 'POST':
        #修改session
        goods_id = int(request.POST.get('goods_id'))
        goods_num = request.POST.get('goods_num')
        goods_select = request.POST.get('goods_select')

        session_goods = request.session.get('goods')
        for se_goods in session_goods:
            if se_goods[0] == goods_id:
                se_goods[1] = int(goods_num) if goods_num else se_goods[1]
                se_goods[2] = int(goods_select) if goods_select else se_goods[2]
        request.session['goods'] = session_goods
        return JsonResponse({'code': 200, 'msg': '请求成功'})


# 删除购物车
def del_cart(request, id):
    if request.method == 'POST':
        session_goods = request.session.get('goods')
        for se_goods in session_goods:
            if se_goods[0] == id:
                session_goods.remove(se_goods)
                break
        request.session['goods'] = session_goods
        ShoppingCart.objects.filter(goods_id=id).delete()
        return JsonResponse({'code':200, 'msg':'请求成功'})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    {% block css %}
    {% endblock %}

    {% block js1 %}
    {% endblock %}

</head>
<body>
    {% block header %}
    {% endblock %}

    {% block search %}
    {% endblock %}

    {% block content %}
    {% endblock %}

    {% block js2 %}
    {% endblock %}

</body>
</html>

templates/base_main.html
{% extends 'base.html' %}

{% block css %}
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
{% endblock %}

{% block js1 %}
    <script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
{% endblock %}

{% block header %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_info fl" {% if user.id %} style="display:block;" {% endif %}>
					欢迎您：<em>{{ user.username }}</em>
					<span>|</span>
					<a href="{% url 'user:logout' %}">退出</a>
				</div>
				<div class="login_btn fl"  {% if user.id %} style="display:none;" {% endif %}>
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user_center_info' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:cart' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'order:order' %}">我的订单</a>
				</div>

			</div>
		</div>
	</div>
{% endblock %}

{% block search %}
    <div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cart:cart' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">1</div>
		</div>
		<script>
			$.get('/cart/cart_num/', function(data){
				if (data.code == '200'){
					$('#show_count').text(data.count)
				}
			})

		</script>
	</div>
{% endblock %}

{% block footer %}
	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p> 水果蔬菜牛奶好</p>
		<p>电话：</p>
	</div>
{% endblock %}

{% block js2 %}
{% endblock %}

templates/cart.html
{% extends 'base_main.html' %}

{% block title %}
	天天生鲜 -- 购物车
{% endblock %}

{% block search %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;购物车</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>
{% endblock %}


{% block content %}
	<div class="total_count">全部商品<em>2</em>件</div>	
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>
	{% for goods in result %}
		<ul class="cart_list_td clearfix" id="goods_{{goods.0.id}}">
			<li class="col01"><input type="checkbox" name="" {% if goods.2 %} checked {% endif %}></li>
			<li class="col02"><img src="/media/{{ goods.0.goods_front_image }}"></li>
			<li class="col03">{{ goods.0.name }}<br><em>{{ goods.0.shop_price }}元/500g</em></li>
			<li class="col04">500g</li>
			<li class="col05">{{ goods.0.shop_price }}元</li>
			<li class="col06">
				<div class="num_add">
					<a href="javascript:;" class="add fl" onclick="add_cart({{goods.0.id}})">+</a>
					<input type="text" id="num_show_{{goods.0.id}}" class="num_show fl" value="{{ goods.1 }}">
					<a href="javascript:;" class="minus fl" onclick="sub_cart({{goods.0.id}})">-</a>
				</div>
			</li>
			<li class="col07">{{ goods.3 }}元</li>
			<li class="col08"><a href="javascript:;" onclick="del_cart({{goods.0.id}})">删除</a></li>
		</ul>
	{% endfor %}

	<ul class="settlements">
		<li class="col01"><input type="checkbox" name="" checked=""></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em>42.60</em><br>共计<b>2</b>件商品</li>
		<li class="col04"><a href="{% url 'order:place_order' %}">去结算</a></li>
	</ul>
	{% csrf_token %}
	<script>
		function cart_price(){
			$.get('/cart/cart_price/',function(data){
				if(data.code == '200'){
					$('.total_count em').html(data.all_total)
					$('.settlements .col03 em').html(data.all_price)
					$('.settlements .col03 b').html(data.is_select_num)
				}
			})
		}
		cart_price()
		<!--添加-->
		function add_cart(id){
			var num = $('#num_show_' + id).val()
			var new_num = parseInt(num) + 1
			$('#num_show_' + id).val(new_num)
			change_cart(id, new_num)
		}
		<!--减少商品数量-->
		function sub_cart(id){
			var num = $('#num_show_' + id).val()
			if(parseInt(num) > 1){
				var new_num = parseInt(num) - 1
				$('#num_show_' + id).val(new_num)
				change_cart(id, new_num)

			}
		}
		<!--修改数量或者选择状态-->
		function change_cart(id, new_num){
			var csrf = $('input[name="csrfmiddlewaretoken"]').val()
			$.ajax({
				url:'/cart/change_cart/',
				type:'POST',
				data:{'goods_id':id, 'goods_num': new_num},
				headers:{'X-CSRFToken': csrf},
				dataType:'json',
				success:function(data){
					cart_price()
				},
				error:function(data){

				}
			})
		}
		<!--删除-->
		function del_cart(id){
			var csrf = $('input[name="csrfmiddlewaretoken"]').val()
			$.ajax({
				url:'/cart/del_cart/' + id + '/',
				type:'POST',
				headers:{'X-CSRFToken': csrf},
				dataType:'json',
				success:function(data){
					$('#goods_' + id).remove()
				},
				error:function(data){
					alert('失败')
				}
			})
		}
	</script>
{% endblock %}

templates/detail.html
{% extends 'base_main.html' %}

{% block title %}
	商品详情
{% endblock %}


{% block content %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
					<li><a href="#" class="fruit">新鲜水果</a></li>
					<li><a href="#" class="seafood">海鲜水产</a></li>
					<li><a href="#" class="meet">猪牛羊肉</a></li>
					<li><a href="#" class="egg">禽类蛋品</a></li>
					<li><a href="#" class="vegetables">新鲜蔬菜</a></li>
					<li><a href="#" class="ice">速冻食品</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">新鲜水果</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="/media/{{ goods.goods_front_image }}"></div>

		<div class="goods_detail_list fr">
			<h3>{{ goods.name }}</h3>
			<p>{{ goods.goods_brief }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{ goods.shop_price }}</em></span>
				<span class="show_unit">单  位：500g</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1">
					<a href="javascript:;" class="add fr" onclick="add_goods()">+</a>
					<a href="javascript:;" class="minus fr" onclick="sub_goods()">-</a>
				</div>
				<script>
					function add_goods(){
						var num = $('.num_show').val()
						var new_num = parseInt(num) + 1
						$('.num_show').val(new_num)
					}
					function sub_goods(){
						var num = $('.num_show').val()
						if(parseInt(num) > 1){
							var new_num = parseInt(num) - 1
							$('.num_show').val(new_num)
						}
					}


				</script>
			</div>
			<div class="total">总价：<em>{{ goods.shop_price }}元</em></div>
			<div class="operate_btn">
				<a href="javascript:;" class="buy_btn">立即购买</a>
				<a href="javascript:;" class="add_cart" id="add_cart" onclick="add_cart({{ goods.id }})">加入购物车</a>
			</div>
			{% csrf_token %}
			<script>
				function add_cart(id){
					var num = $('.num_show').val()
					var csrf = $('input[name="csrfmiddlewaretoken"]').val()
					$.ajax({
						url:'/cart/add_cart/',
						type:'POST',
						data:{'goods_id':id, 'goods_num':num},
						dataType:'json',
						headers: {'X-CSRFToken': csrf},
						success: function(data){
							if(data.code == '200'){
								$('#show_count').text(data.count)
							}
						},
						error:function(data){
							alert('失败')
						}
					})
				}

			</script>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
					<li>
						<a href="#"><img src="images/goods/goods001.jpg"></a>
						<h4><a href="#">进口柠檬</a></h4>
						<div class="prize">￥3.90</div>
					</li>
					<li>
						<a href="#"><img src="images/goods/goods002.jpg"></a>
						<h4><a href="#">玫瑰香葡萄</a></h4>
						<div class="prize">￥16.80</div>
					</li>
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd>{{ goods.goods_desc | safe }}</dd>
				</dl>
			</div>

		</div>
	</div>
{% endblock %}

{% block footer %}
    {{ block.super }}
	<div class="add_jump"></div>
{% endblock %}

{% block js2 %}
	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript">
		var $add_x = $('#add_cart').offset().top;
		var $add_y = $('#add_cart').offset().left;

		var $to_x = $('#show_count').offset().top;
		var $to_y = $('#show_count').offset().left;

		$(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})
		$('#add_cart').click(function(){
			$(".add_jump").stop().animate({
				'left': $to_y+7,
				'top': $to_x+7},
				"fast", function() {
					$(".add_jump").fadeOut('fast',function(){
						$('#show_count').html(2);
					});

			});
		})
	</script>
{% endblock %}

templates/index.html
{% extends 'base_main.html' %}

{% block title %}
	天天生鲜-首页
{% endblock %}



{% block js1 %}
{{ block.super }}
	<script type="text/javascript" src="/static/js/jquery-ui.min.js"></script>
	<script type="text/javascript" src="/static/js/slide.js"></script>
{% endblock %}




{% block content %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
			<li><a href="#model01" class="fruit">新鲜水果</a></li>
			<li><a href="#model02" class="seafood">海鲜水产</a></li>
			<li><a href="#model03" class="meet">猪牛羊肉</a></li>
			<li><a href="#model04" class="egg">禽类蛋品</a></li>
			<li><a href="#model05" class="vegetables">新鲜蔬菜</a></li>
			<li><a href="#model06" class="ice">速冻食品</a></li>
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				<li><img src="/static/images/slide.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide02.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide03.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide04.jpg" alt="幻灯片"></li>
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			<a href="#"><img src="/static/images/adv01.jpg"></a>
			<a href="#"><img src="/static/images/adv02.jpg"></a>
		</div>
	</div>
	{% for i in result %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model01">{{i.0.category_type}}</h3>

			<a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/media/{{i.0.category_front_image}}"></div>
			<ul class="goods_list fl">
				{% for a in i.1 %}
				<li>
					<h4><a href="{% url 'goods:detail' a.id %}">{{a.name}}</a></h4>
					<a href="{% url 'goods:detail' a.id %}"><img src="/media/{{a.goods_front_image}}"></a>
					<div class="prize">{{a.shop_price}}</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>
	{% endfor %}
{% endblock %}

{% block js2 %}
	<script type="text/javascript" src="/static/js/slide.js"></script>
	<script type="text/javascript">
		BCSlideshow('focuspic');
		var oFruit = document.getElementById('fruit_more');
		var oShownum = document.getElementById('show_count');

		var hasorder = localStorage.getItem('order_finish');

		if(hasorder)
		{
			oShownum.innerHTML = '2';
		}

		oFruit.onclick = function(){
			window.location.href = 'list.html';
		}
	</script>
{% endblock %}

templates/login.html
{% extends 'base_main.html' %}

{% block title %}
登录
{% endblock %}

{% block content %}
	<div class="login_top clearfix">
		<a href="index.html" class="login_logo"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="#">立即注册</a>
				</div>
				<div class="form_input">
					<form action="" method="post">
						{% csrf_token %}
						<input type="text" name="username" class="name_input" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>

{% endblock %}

templates/place_order.html
{% extends 'base_main.html' %}

{% block title %}
	结算
{% endblock %}

{% block search %}
	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;提交订单</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>
{% endblock %}

{% block content %}
	<h3 class="common_title">确认收货地址</h3>

	<div class="common_list_con clearfix">
		<dl>
			<dt>寄送到：</dt>
			<dd><input type="radio" name="" checked="">北京市 海淀区 东北旺西路8号中关村软件园 （李思 收） 182****7528</dd>
		</dl>
		<a href="{% url 'user:user_site' %}" class="edit_site">编辑收货地址</a>

	</div>
	
	<h3 class="common_title">支付方式</h3>	
	<div class="common_list_con clearfix">
		<div class="pay_style_con clearfix">
			<input type="radio" name="pay_style" checked>
			<label class="cash">货到付款</label>
			<input type="radio" name="pay_style">
			<label class="weixin">微信支付</label>
			<input type="radio" name="pay_style">
			<label class="zhifubao"></label>
			<input type="radio" name="pay_style">
			<label class="bank">银行卡支付</label>
		</div>
	</div>

	<h3 class="common_title">商品列表</h3>
	
	<div class="common_list_con clearfix">
		<ul class="goods_list_th clearfix">
			<li class="col01">商品名称</li>
			<li class="col02">商品单位</li>
			<li class="col03">商品价格</li>
			<li class="col04">数量</li>
			<li class="col05">小计</li>		
		</ul>
		{% for cart in carts %}
		<ul class="goods_list_td clearfix">
			<li class="col01">{{ forloop.counter }}</li>
			<li class="col02"><img src="/media/{{ cart.goods.goods_front_image }}"></li>
			<li class="col03">{{  cart.goods.name }}</li>
			<li class="col04">500g</li>
			<li class="col05">{{ cart.goods.shop_pricr }}元</li>
			<li class="col06">{{ cart.nums }}</li>
			<li class="col07">{{ cart.goods_price }}元</li>
		</ul>
		{% endfor %}
	</div>

	<h3 class="common_title">总金额结算</h3>

	<div class="common_list_con clearfix">
		<div class="settle_con">
			<div class="total_goods_count">共<em>2</em>件商品，总金额<b>{{ total_price }}元</b></div>
			<div class="transit">运费：<b>10元</b></div>
			<div class="total_pay">实付款：<b>{{ total_price | add:"10" }}元</b></div>
		</div>
	</div>

	<div class="order_submit clearfix">
		<a href="javascript:;" id="order_btn">提交订单</a>
	</div>
{% endblock %}

{% block footer %}
{{ block.super }}
	<div class="popup_con">
		<div class="popup">
			<p>订单提交成功！</p>
		</div>
		<div class="mask"></div>
	</div>

{% endblock %}
{% block js2 %}
	<div class="popup_con">
		<div class="popup">
			<p>订单提交成功！</p>
		</div>
		
		<div class="mask"></div>
	</div>
	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript">
		$('#order_btn').click(function() {
			localStorage.setItem('order_finish',2);

			address_radio = $('input[name="address"]')
			for(var i=0; i<address_radio.length; i++){
				if(address_radio[i].checked == true){
					var value = address_radio[i].value
				}
			}
			if(value){
				var csrf = $('input[name="csrfmiddlewaretoken"]').val();
				$.ajax({
					url:'/order/make_order/',
					type:'POST',
					dataType:'json',

					headers:{'X-CSRFToken':csrf},
					success:function(data){
						alert('hehe')
					},
					error:function(data){
						alert('sb')
					}
				})

			$('.popup_con').fadeIn('fast', function() {

				setTimeout(function(){
					$('.popup_con').fadeOut('fast',function(){
						window.location.href = 'index.html';
					});	
				},3000)
				
			});
		});
	</script>
{% endblock %}